server:
  port: 8080

is_server_running_behind_proxy: false

mongodb:
  connection_caching: true
  uri: "mongodb+srv://saidunna450:Saisagar%40123@cluster0.ww2edzo.mongodb.net/interviewDB?retryWrites=true&w=majority&appName=Cluster0"

web_app_host: 'http://localhost:3000'

logger:
  transports: ['console']

accounts:
  token_signing_key: 'JWT_TOKEN'
  token_expiry_days: 1
  token_expires_in_seconds: 3600
  create_test_user_account: true
  test_user:
    first_name: "Test"
    last_name: "User"
    username: "test@example.com"
    password: "testpassword"

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  datadog:
    enabled: 'false'

BOOTSTRAP_APP: true
