logger:
  transports: ['console']

mongodb:
  uri: 'mongodb+srv://saidunna450:Saisagar%40123@cluster0.ww2edzo.mongodb.net/interviewDB?retryWrites=true&w=majority&appName=Cluster0'

temporal:
  server_address: 'localhost:7233'

sms:
  enabled: false

is_server_running_behind_proxy: false

public:
  authenticationMechanism: 'EMAIL' #or 'PHONE'
  default_otp:
    enabled: true
    code: '1234'

account:
  enable_bootstrap_tasks: true
  create_test_user_account: true
  test_user:
    first_name: "Test"
    last_name: "User"
    username: "test@example.com"
    password: "testpassword"

BOOTSTRAP_APP: true
